server:
  port: 8081

langchain4j:
  community:
    dashscope:
      chat-model:
        api-key: sk-75815a19a3f946ce994c3ebaa5fa91e1
        model-name: qwen-max
      embedding-model:
        api-key: sk-75815a19a3f946ce994c3ebaa5fa91e1
        #model: multimodal-embedding-v1
        model: text-embedding-v2


pgvector:
  database: postgres
  host: localhost
  port : 5433
  user: postgres
  password: postgres
  table: vector_store

logging:
  level:
    root: DEBUG
    # LangChain4j 核心模块
    dev.langchain4j: DEBUG
    # 若使用 OpenAI 集成
    dev.langchain4j.model.openai: DEBUG